/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Financiera.Datos;
import dominio.Cliente;
import dominio.Credito;
import java.util.ArrayList;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alech
 */
public class VentanaCliente extends javax.swing.JFrame {
    
    /**
     *
     */
    private Datos datos = new Datos();
    private String clienteDNI;
    /**
     * Creates new form VentanaCliente
     */
    public VentanaCliente() {
        initComponents();
        lblCliente.setText("DNI: ");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        lblCliente = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nuevoPago = new javax.swing.JButton();
        lblDomicilio = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID credito", "Cantidad de cuotaas", "Interes", "Estado del credito", "Monto entregado", "Monto total"
            }
        ));
        jScrollPane1.setViewportView(tablaCliente);

        lblCliente.setText("Cliente:");
        lblCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblClienteKeyReleased(evt);
            }
        });

        lblDNI.setText("DNI:");

        nuevoPago.setText("Ingresar pago");
        nuevoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoPagoActionPerformed(evt);
            }
        });

        lblDomicilio.setText("Domiciolio:");

        lblTel.setText("Telefono:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nuevoPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTel)
                    .addComponent(lblDomicilio)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCliente)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDNI)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel4)
                        .addGap(295, 295, 295)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDNI)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDomicilio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTel)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(nuevoPago))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        VentanaDNI ventdni = new VentanaDNI();
        ventdni.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void nuevoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoPagoActionPerformed

    private void lblClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblClienteKeyReleased

    }//GEN-LAST:event_lblClienteKeyReleased

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblDomicilio;
    private javax.swing.JLabel lblTel;
    private javax.swing.JButton nuevoPago;
    private javax.swing.JTable tablaCliente;
    // End of variables declaration//GEN-END:variables

    private void mostrarVenta(Credito c) {
            DefaultTableModel mat = (DefaultTableModel) tablaCliente.getModel();
            mat.addRow(new Object[]{
                /*venta.getContadorProductos(),
                p.getDescripcionProducto(),
                p.getPrecio(),
                p.revisarAgregado("Jamon"),
                p.revisarAgregado("Queso"),
                p.revisarAgregado("Huevo"),
                p.calcularTotalPremiuns(),
                p.getPrecio() +  p.calcularTotalPremiuns()*/
            });
            //lblTotal.setText("$ "+venta.calcularTotal());
    }

    public VentanaCliente(String clienteDNI) {
        this.clienteDNI = clienteDNI;
        initComponents();
        lblDNI.setText("DNI de cliente: " + clienteDNI);
        for(Cliente c : datos.getListaClientes()){
            if (c.getDNI() == Integer.parseInt(clienteDNI)){
                lblCliente.setText("Nombre Cliente: " + c.getNombre());
                lblDomicilio.setText("Domicilio: " + c.getDomicilio());
                lblTel.setText("Telefono: "+ c.getTelefono());
            }
        }
    }



}
