/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dominio.Credito;

/**
 *
 * @author alech
 */
public class VentanaComprobante extends javax.swing.JFrame {

    /**
     * Creates new form VentanaComprobante
     */
    private Credito credito;

    public VentanaComprobante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMonto = new javax.swing.JLabel();
        lblPlan = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblCuota = new javax.swing.JLabel();
        lblMontoEntregado = new javax.swing.JLabel();
        lblGastoAdmin = new javax.swing.JLabel();
        Finalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMonto.setText("Monto");

        lblPlan.setText("Plan");

        lblTotal.setText("Total");

        lblCuota.setText("Cuota");

        lblMontoEntregado.setText("MontoEntrgado");

        lblGastoAdmin.setText("GastoAdmin");

        Finalizar.setText("Finalizar");
        Finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMonto)
                    .addComponent(lblPlan)
                    .addComponent(lblTotal)
                    .addComponent(lblCuota)
                    .addComponent(lblMontoEntregado)
                    .addComponent(lblGastoAdmin))
                .addContainerGap(334, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Finalizar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblMonto)
                .addGap(18, 18, 18)
                .addComponent(lblPlan)
                .addGap(18, 18, 18)
                .addComponent(lblTotal)
                .addGap(18, 18, 18)
                .addComponent(lblCuota)
                .addGap(18, 18, 18)
                .addComponent(lblMontoEntregado)
                .addGap(18, 18, 18)
                .addComponent(lblGastoAdmin)
                .addGap(26, 26, 26)
                .addComponent(Finalizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarActionPerformed
        VentanaDNI ventanadni = new VentanaDNI();
        ventanadni.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_FinalizarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Finalizar;
    private javax.swing.JLabel lblCuota;
    private javax.swing.JLabel lblGastoAdmin;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblMontoEntregado;
    private javax.swing.JLabel lblPlan;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables

    public VentanaComprobante(Credito credito) {
        this.credito = credito;
        initComponents();
        String s;
        if (credito.getPlan().isEsadelantado()) {
            s = "(primera adelantada)";
            lblGastoAdmin.setVisible(false);
        } else {
            s = "(primera vencida)";
            lblGastoAdmin.setText("Importe de gastos: $" + credito.getGastosadmin());
        }
        lblCuota.setText("Importe de cuota: $" + String.format("%.2f", credito.getCuotas().get(0).getPrecio()));
        lblMonto.setText("Monto solicitado: $" + credito.getMontosolicitado());
        lblMontoEntregado.setText("Importe entregado al cliente: $" + credito.getMontoaentregar());
        lblPlan.setText("Plan: "
                + credito.getPlan().getCantcuotas()
                + " Cuotas "
                + s 
                + " - Porc. gastos: " 
                + (credito.getPlan().getGastosadmin()*100) 
                + "% - Int. Men. : "
                + (credito.getPlan().getInteres()*100)
                + "%"
            );
        lblTotal.setText("Monto total del crédito: $ " + credito.getTotal());
    }

}
